In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array(["hello", True, 3.14])

array(['hello', 'True', '3.14'], dtype='<U32')

In [5]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [6]:
print(arr1.shape)
print(arr2.shape)

(3,)
(2, 3)


In [7]:
print(arr1.size)
print(arr2.size)

3
6


In [8]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.arange(5, 10, 2)

array([5, 7, 9])